---
services:
  postgres-9.6:
    image: postgres:9.6.1
    ports:
      - "7001:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - ./db/postgres-9.6-data:/var/lib/postgresql/data
      - ./db/transient:/var/www/db
    networks:
      - rapid1-db

  postgres-13:
    image: postgres:13.14
    ports:
      - "7002:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - ./db/postgres-13-data:/var/lib/postgresql/data
      - ./db/transient:/var/www/db/transient
      - ./db/original:/var/www/db/original
    networks:
      - rapid1-db
networks:
  rapid1-db:
    driver: bridge
